(function (ng) {
    var mod = ng.module('ordenModule', ['ngCrud']);

    mod.constant('ordenContext', 'ordens');

    mod.constant('ordenModel', {
        fields: [{
                name: 'name',
                displayName: 'Name',
                type: 'String',
                required: true
            }, {
                name: 'manejoCreditoConsumo',
                displayName: 'ManejoCreditoConsumo',
                type: 'Boolean',
                required: true
            }, {
                name: 'manejoCreditoComercial',
                displayName: 'ManejoCreditoComercial',
                type: 'Boolean',
                required: true
            }, {
                name: 'manejoCreditoLibranza',
                displayName: 'ManejoCreditoLibranza',
                type: 'Boolean',
                required: true
            }, {
                name: 'manejoCreditoHipotecario',
                displayName: 'ManejoCreditoHipotecario',
                type: 'Boolean',
                required: true
            }, {
                name: 'manejoMicrocredito',
                displayName: 'ManejoMicrocredito',
                type: 'Boolean',
                required: true
            }, {
                name: 'fechaRegistroOrden',
                displayName: 'FechaRegistroOrden',
                type: 'Date',
                required: true
            }, {
                name: 'fechaInicioFacturacion',
                displayName: 'FechaInicioFacturacion',
                type: 'Date',
                required: true
            }, {
                name: 'estadoOrden',
                displayName: 'EstadoOrden',
                type: 'Integer',
                required: true
            }, {
                name: 'idCoreCartera',
                displayName: 'IdCoreCartera',
                type: 'String',
                required: true
            }, {
                name: 'usuarioCoreCartera',
                displayName: 'UsuarioCoreCartera',
                type: 'String',
                required: true
            }, {
                name: 'urlCoreCartera',
                displayName: 'UrlCoreCartera',
                type: 'String',
                required: true
            }, {
                name: 'numeroUsuariosInicial',
                displayName: 'NumeroUsuariosInicial',
                type: 'Integer',
                required: true
            }, {
                name: 'numeroCreditosInicial',
                displayName: 'NumeroCreditosInicial',
                type: 'Integer',
                required: true
            }, {
                name: 'valorCarteraInicial',
                displayName: 'ValorCarteraInicial',
                type: 'Integer',
                required: true
            }]});
})(window.angular);
